#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: https://eddiecmurray.github.io
baseurl: /blog
title: Eddie Murray
description: Educational technology specialist, running enthusiast, technology geek.
avatar: /assets/img/profile_thumbnail.jpg
# favicon: /favicon.ico
favicon: /assets/img/profile_thumbnail.jpg
# language: ja
language: en

#
# Icons
#
icons:
  rss: true
  email:
  github:
  bitbucket:
  twitter: 
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: https://www.linkedin.com/in/eddiecmurray/ # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: G-HX1XRS2TZ1
disqus:

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: false
  facebook: false # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url: //ttskch.github.io/jekyll-ttskch-theme/assets/img/profile_thumbnail.jpg
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Plugins.
#
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
  - jekyll-tagging-related_posts

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
